apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spring-k8s-argocd
  namespace: argocd
spec:
  description: "Project for spring-k8s-argocd applications"
  sourceRepos:
    - "*"  # Adjust to limit to specific repos
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-k8s-argocd
  namespace: argocd
spec:
  project: spring-k8s-argocd

  source:
    repoURL: https://github.com/nguyebr/spring-argocd-app
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-k8s-argocd

  # source:
  #   repoURL: 123456789012.dkr.ecr.eu-central-1.amazonaws.com
  #   targetRevision: 0.1.0
  #   chart: example-chart
  # destination:
  #   server: 'https://kubernetes.default.svc'
  #   namespace: default    

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
