apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-k8s-argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-deployment-channel
spec:
  project: default

  source:
    repoURL: https://github.com/nguyebr/spring-argocd-app
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-spring-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true