apiVersion: v1
kind: Service
metadata:
  name: spring-argocd-app
spec:
  selector:
    app: spring-argocd-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-app
spec:
  selector:
    matchLabels:
      app: spring-argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-argocd-app
        app-temp: spring-argocd-app
        app.kubernetes.io/instance: spring-argocd-app
        app.kubernetes.io/name: spring-argocd-app
        app.kubernetes.io/version: v0.1.0
    spec:
      containers:
        - name: spring-argocd-app
          image: 874542566772.dkr.ecr.us-east-1.amazonaws.com/sample/spring-argocd-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
